wandb_version: 1

K:
  desc: null
  value: 512
N:
  desc: null
  value: 100
_action_groups:
  desc: null
  value:
  - <argparse._ArgumentGroup object at 0x7f8f5cd52430>
  - <argparse._ArgumentGroup object at 0x7f8f5cdf6df0>
_actions:
  desc: null
  value:
  - _StoreAction(option_strings=['--dataset'], dest='dataset', nargs=None, const=None,
    default='halfcheetah-medium-expert-v2', type=<class 'str'>, choices=None, help='(str,
    default=halfcheetah-medium-expert-v2) ', metavar=None)
  - _StoreAction(option_strings=['--config'], dest='config', nargs=None, const=None,
    default='config.vqvae', type=<class 'str'>, choices=None, help='(str, default=config.vqvae)
    ', metavar=None)
  - _HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None,
    default='==SUPPRESS==', type=None, choices=None, help='show this help message
    and exit', metavar=None)
_annotations:
  desc: null
  value:
    config: builtins.str
    dataset: builtins.str
_defaults:
  desc: null
  value: {}
_explicit_bool:
  desc: null
  value: false
_has_negative_number_optionals:
  desc: null
  value: []
_initialized:
  desc: null
  value: true
_mutually_exclusive_groups:
  desc: null
  value: []
_negative_number_matcher:
  desc: null
  value: re.compile('^-\\d+$|^-\\d*\\.\\d+$')
_option_string_actions:
  desc: null
  value:
    --config: _StoreAction(option_strings=['--config'], dest='config', nargs=None,
      const=None, default='config.vqvae', type=<class 'str'>, choices=None, help='(str,
      default=config.vqvae) ', metavar=None)
    --dataset: _StoreAction(option_strings=['--dataset'], dest='dataset', nargs=None,
      const=None, default='halfcheetah-medium-expert-v2', type=<class 'str'>, choices=None,
      help='(str, default=halfcheetah-medium-expert-v2) ', metavar=None)
    --help: _HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None,
      default='==SUPPRESS==', type=None, choices=None, help='show this help message
      and exit', metavar=None)
    -h: _HelpAction(option_strings=['-h', '--help'], dest='help', nargs=0, const=None,
      default='==SUPPRESS==', type=None, choices=None, help='show this help message
      and exit', metavar=None)
_optionals:
  desc: null
  value: <argparse._ArgumentGroup object at 0x7f8f5cdf6df0>
_parsed:
  desc: null
  value: true
_positionals:
  desc: null
  value: <argparse._ArgumentGroup object at 0x7f8f5cd52430>
_registries:
  desc: null
  value:
    action:
      append: argparse._AppendAction
      append_const: argparse._AppendConstAction
      count: argparse._CountAction
      extend: argparse._ExtendAction
      help: argparse._HelpAction
      'null': argparse._StoreAction
      parsers: argparse._SubParsersAction
      store: argparse._StoreAction
      store_const: argparse._StoreConstAction
      store_false: argparse._StoreFalseAction
      store_true: argparse._StoreTrueAction
      version: argparse._VersionAction
    type:
      'null': argparse.ArgumentParser.__init__.<locals>.identity
_subparser_buffer:
  desc: null
  value: []
_subparsers:
  desc: null
  value: null
_underscores_to_dashes:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.1
    start_time: 1710387385
    t:
      1:
      - 1
      - 55
      3:
      - 15
      - 16
      4: 3.8.1
      5: 0.12.21
      8:
      - 5
action_weight:
  desc: null
  value: 5
add_help:
  desc: null
  value: true
allow_abbrev:
  desc: null
  value: true
args_from_configs:
  desc: null
  value: []
argument_buffer:
  desc: null
  value:
    help:
    - - -h
      - --help
    - action: help
      default: ==SUPPRESS==
      help: show this help message and exit
argument_default:
  desc: null
  value: null
attn_pdrop:
  desc: null
  value: 0.1
batch_size:
  desc: null
  value: 512
bottleneck:
  desc: null
  value: pooling
class_variables:
  desc: null
  value:
    config:
      comment: ''
    dataset:
      comment: ''
commit:
  desc: null
  value: c096a5c6e37f78b918946cf8d26119a08d156c73 main
config:
  desc: null
  value: config.vqvae
conflict_handler:
  desc: null
  value: error
dataset:
  desc: null
  value: halfcheetah-medium-expert-v2
description:
  desc: null
  value: null
device:
  desc: null
  value: cuda
disable_goal:
  desc: null
  value: false
discount:
  desc: null
  value: 0.99
embd_pdrop:
  desc: null
  value: 0.1
epilog:
  desc: null
  value: null
exp_name:
  desc: null
  value: random_name
extra_args:
  desc: null
  value:
  - --exp_name
  - random_name
  - --tag
  - development
  - --seed
  - '2323'
first_action_weight:
  desc: null
  value: 0
formatter_class:
  desc: null
  value: argparse.HelpFormatter
fromfile_prefix_chars:
  desc: null
  value: null
last_value_weight:
  desc: null
  value: 0
latent_step:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.0002
logbase:
  desc: null
  value: /home/v-linjiexu/logs/
lr_decay:
  desc: null
  value: false
ma_update:
  desc: null
  value: true
masking:
  desc: null
  value: uniform
max_path_length:
  desc: null
  value: 1000
model:
  desc: null
  value: VQTransformer
n_embd:
  desc: null
  value: 128
n_epochs_ref:
  desc: null
  value: 50
n_head:
  desc: null
  value: 4
n_layer:
  desc: null
  value: 4
n_saves:
  desc: null
  value: 3
normalize:
  desc: null
  value: true
normalize_reward:
  desc: null
  value: true
obs_shape:
  desc: null
  value:
  - -1
position_weight:
  desc: null
  value: 1
prefix_chars:
  desc: null
  value: '-'
prog:
  desc: null
  value: train.py
resid_pdrop:
  desc: null
  value: 0.1
residual:
  desc: null
  value: true
reward_weight:
  desc: null
  value: 1
savepath:
  desc: null
  value: /home/v-linjiexu/logs/halfcheetah-medium-expert-v2/random_name/
seed:
  desc: null
  value: '2323'
state_conditional:
  desc: null
  value: true
step:
  desc: null
  value: 1
subsampled_sequence_length:
  desc: null
  value: 25
suffix:
  desc: null
  value: ''
sum_reward_weight:
  desc: null
  value: 0
tag:
  desc: null
  value: development
task_type:
  desc: null
  value: locomotion
termination_penalty:
  desc: null
  value: -100
trajectory_embd:
  desc: null
  value: 512
usage:
  desc: null
  value: null
value_weight:
  desc: null
  value: 1
